// Shared game state. Question data is retained independently of rendered cells.
const _dom = {
  questionLength: 15000,
  current_stylesheet: 0,
  is_muted: false,
  editModeToggled: false,
  doublePointToggled: false,
  viewingQuestion: false,
  isOpen: false,
  boardReady: false,
  boardVersion: 0,
  board: [],
  selectedBaseValue: 200,
  default_point_value: 200,
  players: Array.from({length: 3}, (_, i) => ({name: `Player ${i + 1}`, score: 0})),
  main: document.getElementById('main'),
  menu_button: document.getElementById('menu-button'),
  mute_button: document.getElementById('mute-button'),
  unmute_button: document.getElementById('unmute-button'),
  edit_mode_icon: document.getElementById('eidt-mode-icon'),
  double_points_icon: document.getElementById('double-points-icon'),
  question_length_icon: document.getElementById('question-length-icon'),
  question_length_text: document.getElementById('question_length_text'),
  settings_menu: document.querySelector('.settings-menu'),
  editModeSwitch: document.querySelector('.settings-toggle-button-two'),
  doublePointsSwitch: document.querySelector('.settings-toggle-button-three'),
  countdown_music: new Audio(new URL('../assets/countdown.mp3', import.meta.url)),
  times_up: new Audio(new URL('../assets/times-up.mp3', import.meta.url)),
  correct_answer_sound: new Audio(new URL('../assets/correct.mp3', import.meta.url)),
};
const _themes = ['default', 'light', 'purple'];
export {_dom, _themes};
